# 开启调试模式
debug: true

# 版本号
version: "0.0.1"

# server producer配置
server:
  # http服务端口
  addr: ":8020"
  # http服务URL
  url: "http://127.0.0.1:8020"

# client comsumer配置
cli:
  # 队列等待数
  max_waits: 128
  # 任务并发处理数
  max_process: 64

# db store配置
db:
  driver: "mysql"
  source: "root:123456@(127.0.0.1:3306)/utask?charset=utf8mb4"
  max_open_conns: 50
  max_idle_conns: 30
  max_retry_times: 32
  max_lock_time: 300

# redis store配置
redis:
  addr: "127.0.0.1:6379"
  password: ""
  db: 0